# -*- coding: utf-8 -*-
"""AI_Data_Science_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pvJKmV5J0efeWYICWIRJtM8ULAxpzML

# AI_Data_Science_Assistant
"""

!pip install pandas numpy matplotlib seaborn scikit-learn

# libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

from google.colab import files

uploaded = files.upload()

import os
print(os.listdir())

import zipfile

with zipfile.ZipFile('archive (17).zip', 'r') as zip_ref:
    zip_ref.extractall()

import os
print(os.listdir())

for file in os.listdir():
    if file.endswith('.csv'):
        print(file)

# Load Dataset
import pandas as pd

df = pd.read_csv("Titanic-Dataset.csv")

df

# Make your assistant give dataset information
print("Rows:",df.shape[0])

print("Columns:",df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

# Add missing value detection
missing = df.isnull().sum()

print("Missing Values:\n")

print(missing)

# Add dataset statistics
df.describe()

# Create a correlation heatmap
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True
)

plt.show()

# Add assistant question answering
while True:

    question=input(
        "\nData Science Assistant: "
    )

    if question.lower()=="exit":

        print("Goodbye")

        break

    elif "summary" in question.lower():

        print(df.describe())

    elif "missing" in question.lower():

        print(df.isnull().sum())

    elif "columns" in question.lower():

        print(df.columns.tolist())

    elif "shape" in question.lower():

        print(df.shape)

    else:

        print(
            "I don't understand"
        )

# Auto-clean missing values
def clean_missing(df):

    for column in df.columns:

        if df[column].dtype=="object":

            df[column].fillna(
                df[column].mode()[0],
                inplace=True
            )

        else:

            df[column].fillna(
                df[column].mean(),
                inplace=True
            )

    return df

df=clean_missing(df)

print(df.isnull().sum())

# Suggest ML model automatically
def suggest_model(target):

    if df[target].dtype=="object":

        return "Classification problem → Logistic Regression"

    return "Regression problem → Linear Regression"

target=input("Enter target column:")

print(
    suggest_model(target)
)

# Auto-train ML model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

le=LabelEncoder()

for col in df.columns:

    if df[col].dtype=="object":

        df[col]=le.fit_transform(
            df[col].astype(str)
        )

target="Survived"

X=df.drop(target,axis=1)

y=df[target]

x_train,x_test,y_train,y_test= train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model=LogisticRegression(
    max_iter=1000
)

model.fit(
    x_train,
    y_train
)

pred=model.predict(
    x_test
)

accuracy=accuracy_score(
    y_test,
    pred
)

print(
    "Accuracy:",
    accuracy
)

# Generate charts automatically
import matplotlib.pyplot as plt
import seaborn as sns

def generate_chart(df):

    numeric=df.select_dtypes(
        include=["number"]
    )

    plt.figure(figsize=(10,8))

    sns.heatmap(
        numeric.corr(),
        annot=True
    )

    plt.show()

    generate_chart(df)

# Add everything to assistant chat
while True:

    question=input(
        "\nAssistant: "
    )

    if question=="exit":

        break

    elif "summary" in question.lower():

        print(df.describe())

    elif "missing" in question.lower():

        print(df.isnull().sum())

    elif "columns" in question.lower():

        print(df.columns.tolist())

    elif "chart" in question.lower():

        generate_chart(df)

    elif "model" in question.lower():

        print(
            suggest_model(
                "Survived"
            )
        )

    else:

        print(
            "Question not understood"
        )

!pip install streamlit

# Convert to a Streamlit chat app
import streamlit as st
import pandas as pd

st.title(
"AI Data Science Assistant"
)

uploaded=st.file_uploader(
"Upload CSV",
type=["csv"]
)

if uploaded:

    df=pd.read_csv(uploaded)

    st.dataframe(
        df.head()
    )

    question=st.text_input(
    "Ask question"
    )

    if question:

        if "summary" in question:

            st.write(
                df.describe()
            )

        elif "columns" in question:

            st.write(
                df.columns.tolist()
            )

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


st.title("AI Data Science Assistant Agent")

uploaded = st.file_uploader(
    "Upload CSV Dataset",
    type=["csv"]
)

if uploaded:

    df = pd.read_csv(uploaded)

    st.subheader("Dataset Preview")
    st.dataframe(df.head())

    # Dataset information
    st.subheader("Dataset Information")

    st.write(
        "Rows:", df.shape[0]
    )

    st.write(
        "Columns:", df.shape[1]
    )

    st.write(
        "Column Names:"
    )

    st.write(
        df.columns.tolist()
    )

    # Missing values

    st.subheader(
        "Missing Values"
    )

    st.write(
        df.isnull().sum()
    )

    # Auto cleaning

    if st.button(
        "Clean Missing Values"
    ):

        for column in df.columns:

            if df[column].dtype=="object":

                df[column].fillna(
                    df[column].mode()[0],
                    inplace=True
                )

            else:

                df[column].fillna(
                    df[column].mean(),
                    inplace=True
                )

        st.success(
            "Missing values cleaned"
        )

    # Heatmap

    if st.button(
        "Generate Heatmap"
    ):

        numeric = df.select_dtypes(
            include=["number"]
        )

        fig,ax=plt.subplots(
            figsize=(10,8)
        )

        sns.heatmap(
            numeric.corr(),
            annot=True,
            ax=ax
        )

        st.pyplot(fig)

    # Model section

    st.subheader(
        "Auto ML"
    )

    target = st.selectbox(
        "Select Target Column",
        df.columns
    )

    if st.button(
        "Train Model"
    ):

        data=df.copy()

        le=LabelEncoder()

        for col in data.columns:

            if data[col].dtype=="object":

                data[col]=le.fit_transform(
                    data[col].astype(str)
                )

        X=data.drop(
            target,
            axis=1
        )

        y=data[target]

        x_train,x_test,y_train,y_test=(
            train_test_split(
                X,
                y,
                test_size=0.2,
                random_state=42
            )
        )

        model=LogisticRegression(
            max_iter=1000
        )

        model.fit(
            x_train,
            y_train
        )

        pred=model.predict(
            x_test
        )

        accuracy=accuracy_score(
            y_test,
            pred
        )

        st.success(
            f"Model Accuracy: {accuracy:.2f}"
        )

    # Chat section

    st.subheader(
        "Assistant Chat"
    )

    question=st.text_input(
        "Ask something"
    )

    if question:

        if "summary" in question.lower():

            st.write(
                df.describe()
            )

        elif "columns" in question.lower():

            st.write(
                df.columns.tolist()
            )

        elif "missing" in question.lower():

            st.write(
                df.isnull().sum()
            )

        else:

            st.write(
                "Question not understood"
            )

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# from sklearn.preprocessing import LabelEncoder
# from sklearn.linear_model import LogisticRegression
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score
# 
# st.title("AI Data Science Assistant Agent")
# 
# uploaded = st.file_uploader(
#     "Upload CSV Dataset",
#     type=["csv"]
# )
# 
# if uploaded:
# 
#     df = pd.read_csv(uploaded)
# 
#     st.subheader("Dataset Preview")
#     st.dataframe(df.head())
# 
#     st.subheader("Dataset Information")
# 
#     st.write("Rows:", df.shape[0])
#     st.write("Columns:", df.shape[1])
#     st.write(df.columns.tolist())
# 
#     st.subheader("Missing Values")
#     st.write(df.isnull().sum())
# 
#     if st.button("Clean Missing Values"):
# 
#         for column in df.columns:
# 
#             if df[column].dtype=="object":
# 
#                 df[column].fillna(
#                     df[column].mode()[0],
#                     inplace=True
#                 )
# 
#             else:
# 
#                 df[column].fillna(
#                     df[column].mean(),
#                     inplace=True
#                 )
# 
#         st.success("Missing values cleaned")
# 
#     if st.button("Generate Heatmap"):
# 
#         numeric=df.select_dtypes(
#             include=["number"]
#         )
# 
#         fig,ax=plt.subplots(figsize=(10,8))
# 
#         sns.heatmap(
#             numeric.corr(),
#             annot=True,
#             ax=ax
#         )
# 
#         st.pyplot(fig)

!ls

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# streamlit
# pandas
# numpy
# matplotlib
# seaborn
# scikit-learn

!ls

!pip install -r requirements.txt

from google.colab import files
files.download('app.py')

from google.colab import files
files.download('requirements.txt')

from google.colab import files
files.download('Titanic-Dataset.csv')

!./cloudflared tunnel --url http://localhost:8501

!npm install -g localtunnel

!ps -ef | grep streamlit

!streamlit run app.py

!ps -ef | grep streamlit

!ps -ef | grep streamlit

!streamlit run app.py

!./cloudflared tunnel --url http://localhost:8501